export const SET_USERPROFILE = 'SET_USERPROFILE';
export const SET_ALBUM = 'SET_ALBUM';
export const SET_PHOTOS = 'SET_PHOTOS';
export const FACEBOOK_LOGOUT = 'FACEBOOK_LOGOUT';
export const CLEAR_USERPROFILE = 'CLEAR_USERPROFILE';
